nginx:
  ports:
    - '80:80'

postgres:
  ports:
    - '5432:5432'

# Adding Xdebug config
symfony:
  environment:
    XDEBUG_CONFIG: 'remote_host={YOUR_INET_ADDRESS} idekey=PHPSTORM'
    PHP_IDE_CONFIG: 'serverName=localhost'