symfony:
  build: ./symfony
  volumes:
    - ./symfony:/var/www/html:rw
  links:
    - mailhog
    - postgres
  environment:
    DATABASE_HOST: postgres
    DATABASE_NAME: projet_3
    DATABASE_USER: projet_3
    DATABASE_PASSWORD: Projet_3
    MAILER_HOST: mailhog
    MAILER_PORT: 1025
    SECRET: ThisIsTheProject_3
    XDEBUG_CONFIG: 'remote_host=192.168.1.29 idekey=PHPSTORM'
    PHP_IDE_CONFIG: 'serverName=localhost'

nginx:
  build: ./ngnix
  volumes:
    - ./ngnix:/var/www/html:rw
  ports:
    - "8000:80"
  links:
    - symfony

postgres:
  image: postgres:9.5
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: projet_3
    POSTGRES_PASSWORD: Projet_3

mailhog:
  image: mailhog/mailhog
