symfony:
  build: ./symfony
  volumes:
    - ./symfony:/var/www/html:rw
  links:
    - mailhog
    - postgres
  environment:
    DATABASE_HOST: postgres
    DATABASE_NAME: le_louvre
    DATABASE_USER: le_louvre
    DATABASE_PASSWORD: le_louvre
    MAILER_HOST: mailhog
    MAILER_PORT: 1025
    SECRET: ThisIsTheProject_3
    XDEBUG_CONFIG: 'remote_host=192.168.1.29 idekey=PHPSTORM'
    PHP_IDE_CONFIG: 'serverName=localhost'

nginx:
  build: ./ngnix
  volumes:
    - "./symfony:/var/www/html:rw"
  ports:
    - "80:80"
  links:
    - symfony

postgres:
  image: postgres:9.5
  ports:
    - '5432:5432'
  environment:
    POSTGRES_USER: le_louvre
    POSTGRES_PASSWORD: le_louvre

mailhog:
  image: mailhog/mailhog
